import type {Metadata} from "next";
import "../globals.css";
import localFont from 'next/font/local'


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const neuehaasunica = localFont({
    src: [
        {
            path: './../fonts/neuehaasunica/Neue-Haas-Unica-W1G-Regular.woff',
            weight: '400',
            style: 'normal'

        },
        {
            path: './../fonts/neuehaasunica/Neue-Haas-Unica-W1G-Medium.woff',
            weight: '500',
            style: 'normal'

        },
        {
            path: './../fonts/neuehaasunica/Neue-Haas-Unica-W1G-Italic.woff',
            weight: '400',
            style: 'italic'

        },
    ],
    variable: '--font-neuehaasunica',
})


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body
            className={`${neuehaasunica.variable} ${neuehaasunica.variable} antialiased flex relative flex-col px-4 w-full`}
        >
        {children}

        </body>
        </html>
    );
}
